Repository sparta-fractal/fractal, pull requests merged in 2025-10, with the labels that each got.

#93 bug/basic: recreate build.gradle
  build.gradle
Labels: bug🐞

#97 feat/tag: implement user tracking for tag views to prevent abuse
  src/main/java/com/sparta/team5/fractal/common/config/CacheConfig.java
  src/main/java/com/sparta/team5/fractal/common/entity/BaseEntity.java
  src/main/java/com/sparta/team5/fractal/domain/product/controller/ProductController.java
  src/main/java/com/sparta/team5/fractal/domain/product/entity/Product.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductService.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductServiceApi.java
  src/main/java/com/sparta/team5/fractal/domain/tag/controller/TagControllerV2.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagProductService.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagProductServiceV2.java
Labels: feature🚀

#102 refactor/common: improve package structure
  src/main/java/com/sparta/team5/fractal/common/core/dto/ApiPageResponse.java
  src/main/java/com/sparta/team5/fractal/common/core/dto/ApiResponse.java
  src/main/java/com/sparta/team5/fractal/common/core/dto/AuthUser.java
  src/main/java/com/sparta/team5/fractal/common/core/entity/BaseEntity.java
  src/main/java/com/sparta/team5/fractal/common/core/exception/CommonErrorCode.java
  src/main/java/com/sparta/team5/fractal/common/core/exception/ErrorCode.java
  src/main/java/com/sparta/team5/fractal/common/core/exception/GlobalException.java
  src/main/java/com/sparta/team5/fractal/common/core/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/team5/fractal/common/crosscutting/annotation/Auth.java
  src/main/java/com/sparta/team5/fractal/common/crosscutting/aop/CacheEvictAspect.java
  src/main/java/com/sparta/team5/fractal/common/infra/cache/CacheConfig.java
  src/main/java/com/sparta/team5/fractal/common/infra/cache/CacheUtil.java
  src/main/java/com/sparta/team5/fractal/common/infra/jpa/JpaAuditingConfig.java
  src/main/java/com/sparta/team5/fractal/common/infra/scheduler/SchedulerConfig.java
  src/main/java/com/sparta/team5/fractal/common/infra/security/AuthUserArgumentResolver.java
  src/main/java/com/sparta/team5/fractal/common/infra/security/JwtFilter.java
  src/main/java/com/sparta/team5/fractal/common/infra/security/JwtUtil.java
  src/main/java/com/sparta/team5/fractal/common/infra/security/PasswordEncoder.java
  src/main/java/com/sparta/team5/fractal/common/infra/web/FilterConfig.java
  src/main/java/com/sparta/team5/fractal/common/infra/web/WebConfig.java
  src/main/java/com/sparta/team5/fractal/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/team5/fractal/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/sparta/team5/fractal/domain/auth/service/AuthService.java
  src/main/java/com/sparta/team5/fractal/domain/auth/service/AuthServiceApi.java
  src/main/java/com/sparta/team5/fractal/domain/category/controller/CategoryController.java
  src/main/java/com/sparta/team5/fractal/domain/category/controller/CategoryControllerV2.java
  src/main/java/com/sparta/team5/fractal/domain/category/entity/Category.java
  src/main/java/com/sparta/team5/fractal/domain/category/exception/CategoryErrorCode.java
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryProductService.java
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryProductServiceV2.java
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryService.java
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryServiceV2.java
  src/main/java/com/sparta/team5/fractal/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/team5/fractal/domain/comment/service/CommentService.java
  src/main/java/com/sparta/team5/fractal/domain/product/controller/ProductControllerV1.java
  src/main/java/com/sparta/team5/fractal/domain/product/controller/ProductControllerV2.java
  src/main/java/com/sparta/team5/fractal/domain/product/entity/Product.java
  src/main/java/com/sparta/team5/fractal/domain/product/exception/ProductErrorCode.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductCacheService.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductServiceV1.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductServiceV2.java
  src/main/java/com/sparta/team5/fractal/domain/tag/controller/TagController.java
  src/main/java/com/sparta/team5/fractal/domain/tag/controller/TagControllerV2.java
  src/main/java/com/sparta/team5/fractal/domain/tag/exception/TagErrorCode.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagProductService.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagProductServiceV2.java
  src/main/java/com/sparta/team5/fractal/domain/user/controller/UserController.java
  src/main/java/com/sparta/team5/fractal/domain/user/entity/User.java
  src/main/java/com/sparta/team5/fractal/domain/user/exception/UserErrorCode.java
  src/main/java/com/sparta/team5/fractal/domain/user/service/UserService.java
  src/test/java/com/sparta/team5/fractal/domain/user/service/UserServiceTest.java
Labels: refactor🔨

#106 refactor/tag: cleanup across all classes
  src/main/java/com/sparta/team5/fractal/domain/tag/controller/TagControllerV1.java
  src/main/java/com/sparta/team5/fractal/domain/tag/controller/TagControllerV2.java
  src/main/java/com/sparta/team5/fractal/domain/tag/repository/TagRepository.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagCacheService.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagProductServiceV1.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagProductServiceV2.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagService.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagServiceApi.java
Labels: refactor🔨

#109 docs/license: create LICENSE
  LICENSE
Labels: docs📚

#110 refactor/basic: cleancode
  src/main/java/com/sparta/team5/fractal/FractalApplication.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductCacheService.java
  src/main/java/com/sparta/team5/fractal/domain/tag/controller/TagControllerV1.java
  src/main/java/com/sparta/team5/fractal/domain/tag/controller/TagControllerV2.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagProductServiceV1.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagProductServiceV2.java
Labels: refactor🔨

#111 docs/readme: create README.md
  README.md
Labels: docs📚

#112 test/service: add test code for comment and search, improve product test code
  src/main/java/com/sparta/team5/fractal/domain/comment/service/CommentService.java
  src/test/java/com/sparta/team5/fractal/domain/comment/service/CommentServiceTest.java
  src/test/java/com/sparta/team5/fractal/domain/product/controller/ProductControllerTest.java
  src/test/java/com/sparta/team5/fractal/domain/product/dto/ProductResponseTest.java
  src/test/java/com/sparta/team5/fractal/domain/product/entity/ProductTest.java
  src/test/java/com/sparta/team5/fractal/domain/product/service/ProductServiceTest.java
  src/test/java/com/sparta/team5/fractal/domain/search/service/SearchServiceTest.java
Labels: test🧪
