Repository sparta-fractal/fractal, pull requests merged in 2025-09, with the labels that each got.

#3 chore/basic: init settings
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/style.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/java/com/sparta/team5/fractal/common/config/JpaAuditingConfig.java
  src/main/java/com/sparta/team5/fractal/common/entity/BaseEntity.java
  src/main/java/com/sparta/team5/fractal/common/exception/ErrorCode.java
  src/main/java/com/sparta/team5/fractal/common/exception/GlobalException.java
  src/main/java/com/sparta/team5/fractal/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/team5/fractal/common/response/ApiPageResponse.java
  src/main/java/com/sparta/team5/fractal/common/response/ApiResponse.java
  src/main/resources/application.yml
Labels: chore🧹

#15 feat/user: init settings
  src/main/java/com/sparta/team5/fractal/domain/user/entity/User.java
  src/main/java/com/sparta/team5/fractal/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/team5/fractal/domain/user/service/UserService.java
  src/main/java/com/sparta/team5/fractal/domain/user/service/UserServiceApi.java
Labels: feature🚀

#23 chore/basic: delete .github/workflows/ci.yml
  .github/workflows/ci.yml
Labels: chore🧹

#27 docs: create gemini styleguide.me
  .gemini/styleguide.me
Labels: docs📚

#26 Feat/comment init
  src/main/java/com/sparta/team5/fractal/domain/comment/entity/Comment.java
  src/main/java/com/sparta/team5/fractal/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/team5/fractal/domain/comment/service/CommentService.java
  src/main/java/com/sparta/team5/fractal/domain/comment/service/CommentServiceApi.java
Labels: feature🚀

#31 feat/user: implement user profile update
  src/main/java/com/sparta/team5/fractal/domain/user/controller/UserController.java
  src/main/java/com/sparta/team5/fractal/domain/user/dto/request/UpdateUserProfileRequest.java
  src/main/java/com/sparta/team5/fractal/domain/user/dto/response/UpdateUserProfileResponse.java
  src/main/java/com/sparta/team5/fractal/domain/user/entity/User.java
  src/main/java/com/sparta/team5/fractal/domain/user/exception/UserErrorCode.java
  src/main/java/com/sparta/team5/fractal/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/team5/fractal/domain/user/service/UserService.java
  src/main/java/com/sparta/team5/fractal/domain/user/service/UserServiceApi.java
Labels: feature🚀

#33 feat/user: implement password update
  src/main/java/com/sparta/team5/fractal/domain/user/controller/UserController.java
  src/main/java/com/sparta/team5/fractal/domain/user/dto/request/UpdatePasswordRequest.java
  src/main/java/com/sparta/team5/fractal/domain/user/dto/response/UpdatePasswordResponse.java
  src/main/java/com/sparta/team5/fractal/domain/user/entity/User.java
  src/main/java/com/sparta/team5/fractal/domain/user/exception/UserErrorCode.java
  src/main/java/com/sparta/team5/fractal/domain/user/service/UserService.java
Labels: feature🚀

#34 Feat/product create
  src/main/java/com/sparta/team5/fractal/domain/product/controller/ProductController.java
  src/main/java/com/sparta/team5/fractal/domain/product/dto/ProductCreateRequest.java
  src/main/java/com/sparta/team5/fractal/domain/product/dto/ProductResponse.java
  src/main/java/com/sparta/team5/fractal/domain/product/entity/Product.java
  src/main/java/com/sparta/team5/fractal/domain/product/exception/ProductErrorCode.java
  src/main/java/com/sparta/team5/fractal/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductService.java
Labels: feature🚀

#38 feat/comment: comment create
  src/main/java/com/sparta/team5/fractal/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/team5/fractal/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/sparta/team5/fractal/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/sparta/team5/fractal/domain/comment/entity/Comment.java
  src/main/java/com/sparta/team5/fractal/domain/comment/exception/CommentErrorCode.java
  src/main/java/com/sparta/team5/fractal/domain/comment/service/CommentService.java
Labels: feature🚀

#41 feat/comment: comment read
  src/main/java/com/sparta/team5/fractal/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/team5/fractal/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/team5/fractal/domain/comment/service/CommentService.java
Labels: feature🚀

#42 docs: update and rename styleguide.me to styleguide.md
  .gemini/styleguide.md
Labels: docs📚

#43 chore: setup Gemini AI configuration file with code review and behavi…
  .gemini/config.yml
Labels: chore🧹

#44 refactor/user: extract hardcoded success messages to SuccessMessages
  src/main/java/com/sparta/team5/fractal/domain/user/constant/SuccessMessages.java
  src/main/java/com/sparta/team5/fractal/domain/user/controller/UserController.java
  src/main/java/com/sparta/team5/fractal/domain/user/exception/UserErrorCode.java
Labels: refactor🔨

#52 Feat/product delete
  src/main/java/com/sparta/team5/fractal/domain/product/controller/ProductController.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductService.java
Labels: feature🚀

#53 docs: delete copilot-instructions.md
  .github/copilot-instructions.md
Labels: docs📚

#58 feat/tag: implement Tag entity and repository
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductService.java
  src/main/java/com/sparta/team5/fractal/domain/tag/entity/Tag.java
  src/main/java/com/sparta/team5/fractal/domain/tag/repository/TagRepository.java
Labels: feature🚀

#59 feat/category: implement setting
  src/main/java/com/sparta/team5/fractal/domain/category/controller/CategoryController.java
  src/main/java/com/sparta/team5/fractal/domain/category/entity/Category.java
  src/main/java/com/sparta/team5/fractal/domain/category/repository/CategoryRepository.java
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryService.java
  src/main/java/com/sparta/team5/fractal/domain/product/entity/ProductCategory.java
Labels: feature🚀

#63 feat/product: implement category
  src/main/java/com/sparta/team5/fractal/domain/category/controller/CategoryController.java
  src/main/java/com/sparta/team5/fractal/domain/category/dto/CategoryCreateRequest.java
  src/main/java/com/sparta/team5/fractal/domain/category/dto/CategoryMapper.java
  src/main/java/com/sparta/team5/fractal/domain/category/dto/CategoryResponse.java
  src/main/java/com/sparta/team5/fractal/domain/category/entity/Category.java
  src/main/java/com/sparta/team5/fractal/domain/category/exception/CategoryErrorCode.java
  src/main/java/com/sparta/team5/fractal/domain/category/repository/CategoryRepository.java
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryService.java
  src/main/java/com/sparta/team5/fractal/domain/product/dto/ProductCreateRequest.java
  src/main/java/com/sparta/team5/fractal/domain/product/dto/ProductResponse.java
  src/main/java/com/sparta/team5/fractal/domain/product/dto/ProductUpdateRequest.java
  src/main/java/com/sparta/team5/fractal/domain/product/entity/Product.java
  src/main/java/com/sparta/team5/fractal/domain/product/entity/ProductCategory.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductService.java
  src/test/java/com/sparta/team5/fractal/domain/product/controller/ProductControllerTest.java
  src/test/java/com/sparta/team5/fractal/domain/product/dto/ProductResponseTest.java
  src/test/java/com/sparta/team5/fractal/domain/product/entity/ProductTest.java
  src/test/java/com/sparta/team5/fractal/domain/product/service/ProductServiceTest.java
Labels: feature🚀

#68 feat/tag: implement read all tags
  src/main/java/com/sparta/team5/fractal/domain/tag/controller/TagController.java
  src/main/java/com/sparta/team5/fractal/domain/tag/dto/response/TagResponse.java
  src/main/java/com/sparta/team5/fractal/domain/tag/repository/TagRepository.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagService.java
  src/main/java/com/sparta/team5/fractal/domain/user/dto/response/UpdatePasswordResponse.java
  src/main/java/com/sparta/team5/fractal/domain/user/dto/response/UpdateUserProfileResponse.java
  src/test/java/com/sparta/team5/fractal/domain/tag/service/TagServiceTest.java
Labels: feature🚀

#69 feat/tag:search tag-product
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryService.java
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryServiceApi.java
  src/main/java/com/sparta/team5/fractal/domain/product/dto/ProductSimpleResponse.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductService.java
  src/main/java/com/sparta/team5/fractal/domain/tag/controller/TagController.java
  src/main/java/com/sparta/team5/fractal/domain/tag/dto/response/TagProductResponse.java
  src/main/java/com/sparta/team5/fractal/domain/tag/entity/Tag.java
  src/main/java/com/sparta/team5/fractal/domain/tag/exception/TagErrorCode.java
  src/main/java/com/sparta/team5/fractal/domain/tag/repository/TagRepository.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagService.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagServiceApi.java
Labels: feature🚀

#73 hotfix/product: fix product bugs
  src/test/java/com/sparta/team5/fractal/domain/product/controller/ProductControllerTest.java
  src/test/java/com/sparta/team5/fractal/domain/product/dto/ProductResponseTest.java
  src/test/java/com/sparta/team5/fractal/domain/product/service/ProductServiceTest.java
Labels: bug🐞

#75 feat/category:getcategory api create
  src/main/java/com/sparta/team5/fractal/domain/category/controller/CategoryController.java
  src/main/java/com/sparta/team5/fractal/domain/category/dto/CategoryProductResponse.java
  src/main/java/com/sparta/team5/fractal/domain/category/entity/Category.java
  src/main/java/com/sparta/team5/fractal/domain/category/repository/CategoryRepository.java
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryService.java
Labels: feature🚀

#77 bug/category,tag- delete product
  src/main/java/com/sparta/team5/fractal/domain/category/repository/CategoryRepository.java
  src/main/java/com/sparta/team5/fractal/domain/product/entity/Product.java
  src/main/java/com/sparta/team5/fractal/domain/tag/repository/TagRepository.java
Labels: bug🐞

#79 feat/product: search
  src/main/java/com/sparta/team5/fractal/domain/product/controller/ProductController.java
  src/main/java/com/sparta/team5/fractal/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductService.java
  src/main/java/com/sparta/team5/fractal/domain/search/entity/Search.java
  src/main/java/com/sparta/team5/fractal/domain/search/repository/SearchRepository.java
  src/main/java/com/sparta/team5/fractal/domain/search/service/SearchService.java
  src/main/java/com/sparta/team5/fractal/domain/search/service/SearchServiceApi.java
Labels: feature🚀

#82 feat/category tag- add paging
  src/main/java/com/sparta/team5/fractal/domain/category/controller/CategoryController.java
  src/main/java/com/sparta/team5/fractal/domain/category/dto/CategoryProductResponse.java
  src/main/java/com/sparta/team5/fractal/domain/category/repository/CategoryRepository.java
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryProductService.java
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryService.java
  src/main/java/com/sparta/team5/fractal/domain/category/service/CategoryServiceApi.java
  src/main/java/com/sparta/team5/fractal/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductService.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductServiceApi.java
  src/main/java/com/sparta/team5/fractal/domain/tag/controller/TagController.java
  src/main/java/com/sparta/team5/fractal/domain/tag/dto/response/TagProductResponse.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagProductService.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagService.java
  src/main/java/com/sparta/team5/fractal/domain/tag/service/TagServiceApi.java
Labels: feature🚀

#84 bug/product: prevent duplicate entry error on update
  src/main/java/com/sparta/team5/fractal/domain/product/entity/Product.java
Labels: bug🐞

#89 refactor/product search
  build.gradle
  src/main/java/com/sparta/team5/fractal/common/aop/CacheEvictAspect.java
  src/main/java/com/sparta/team5/fractal/common/config/CacheConfig.java
  src/main/java/com/sparta/team5/fractal/common/config/SchedulerConfig.java
  src/main/java/com/sparta/team5/fractal/domain/product/controller/ProductController.java
  src/main/java/com/sparta/team5/fractal/domain/product/controller/ProductControllerV2.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/CacheEvictService.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductService.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductServiceApi.java
  src/main/java/com/sparta/team5/fractal/domain/product/service/ProductServiceV2.java
Labels: refactor🔨
